highlighter: pygments
relative_permalinks: true
markdown: kramdown
baseurl: /keeping-codes

all-category-list: [fundamentals,practice,experiments,war stories]
active-category-list: [practice,experiments]

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
