baseURL = "https://www.digipres.net/"
languageCode = "en-gb"
title = "digipres.net"

theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
unsafe= true

#[[menu.main]]
#    name = "Home"
#    url = "/"
#    weight = 1

[[menu.main]]
    name = "Guides"
    url = "/guides/"
    weight = 3

[[menu.main]]
    name = "Patterns"
    url = "/patterns/"
    weight = 4

[[menu.main]]
    name = "Experiments"
    url = "/experiments/"
    weight = 5

[[menu.main]]
    name = "Foundations"
    url = "/foundations/"
    weight = 6

[[menu.main]]
    name = "Asides"
    url = "/asides/"
    weight = 10


[params]
  mainSections = ['about', 'patterns', 'guides', 'foundations', 'experiments', 'asides']
  google_analytics_id=""
  homepage_button_link = '/guides/'
  homepage_button_text = 'Get Started'
  homepage_intro = 'Patterns and practices for digital preservation.'
#  homepage_image = '/images/terminal.gif'

  [params.homepage_meta_tags]
    meta_description = "digipres.net: patterns and practices for digital preservation."
    meta_og_title = "digipres.net"
    meta_og_type = "website"
    meta_og_url = "https://www.digipres.net"
    meta_og_image = "/images/logo.svg"
    meta_og_description = "digipres.net: patterns and practices for digital preservation."
    meta_twitter_card = "summary"
    meta_twitter_site = "@digipresnet"
    meta_twitter_creator = "@digipresnet"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard = "/images/logo.svg"

