# General settings:
title: Codex
author: Andrew N. Jackson
logo: "images/glider.png"
copyright: "2024"
exclude_patterns: ['_build', '**.ipynb_checkpoints']
only_build_toc_files: true

# Parser settings:
parse:
  myst_enable_extensions:
    - amsmath
#    - attrs_inline
    - colon_fence
    - deflist
    - dollarmath
    - fieldlist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - strikethrough
    - substitution
    - tasklist

# Execution options:
execute:
  timeout: 90
  execute_notebooks: auto

# Link to GitHub:
repository:
  url: https://github.com/anjackson/patterns
  path_to_book: content  # An optional path to your book, defaults to repo root
  branch: main  # An optional branch, defaults to `master`

# Launch button settings:
launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

# HTML settings:
html:
  favicon: images/logo.png
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  home_page_in_navbar: false
  # Support comments (not sure about using this as yet):
  comments:
    utterances:
      repo: "anjackson/codex"
  # Add links and license to footer.
  extra_footer: |
    <p>
    This site is <a href="https://github.com/anjackson/patterns/">open source</a> and open access:<br/>
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>
    </p>

# Additional Sphinx config:
sphinx:
  config:
    html_last_updated_fmt: '%B %d, %Y'
    html_show_copyright: true
    templates_path: _templates
    #html_theme_options: 
      # See https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/layout.html
      #article_header_end: ["metablob.html"]
      # See https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/layout.html#secondary-sidebar-right
      #secondary_sidebar_items: ["page-toc", "page-side-meta", "edit-this-page", "sourcelink"]
  
  extra_extensions:
    - sphinxcontrib.mermaid
#    - sphinx_tippy # Show previews when hovering links
