# General settings:
title: digipres.net
author: Andrew N. Jackson
logo: "images/logo.png"
copyright: "2022"
exclude_patterns: ['_build', '**.ipynb_checkpoints']
only_build_toc_files: true

# Execution options:
execute:
  timeout: 90
  execute_notebooks: cache

# Link to GitHub:
repository:
  url: https://github.com/digipresnet/digipresnet-site
  path_to_book: content  # An optional path to your book, defaults to repo root
  branch: jbook  # An optional branch, defaults to `master`

# Launch button settings:
launch_buttons:
  notebook_interface: "classic"  # or "jupyterlab"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

# HTML settings:
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  home_page_in_navbar: false
  # Support comments (not sure about using this as yet):
  #comments:
  #  utterances:
  #    repo: "digipresnet/digipresnet-site"
  # Add links and license to footer.
  extra_footer: |
    <p>
    This site is <a href="https://github.com/digipresnet/digipresnet-site/">open source</a> and open access:<br/>
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>
    </p>

# Additional Sphinx config:
sphinx:
  config:
    html_show_copyright: true
  extra_extensions:
    - sphinxcontrib.mermaid
